from __future__ import annotations

"""Stateless compatibility facade for vector RAG services.

Callers may keep importing this module.  Types, backend implementation/state,
chunk building, retrieval, reranking, and scheduling each remain owned by their
focused modules and are re-exported here without reflection or duplicate state.
"""

from app.services.vector_build import schedule_vector_rebuild_task
from app.services.vector_chunk_builder import _chunk_text, build_kb_chunk_plan, build_project_chunks
from app.services.vector_rebuild_coordinator import ingest_kb_vectors, rebuild_kb_vectors, run_kb_vector_operation
from app.services.vector_rerank import (
    _rerank_candidates,
    _rerank_score,
    _rerank_tokens,
    _resolve_rerank_config,
    _resolve_rerank_external_config,
)
from app.services.vector_retrieval import (
    _VECTOR_DROPPED_REASON_EXPLAIN,
    _build_vector_query_counts,
    _merge_kb_candidates,
    _merge_kb_candidates_rrf,
    _normalize_kb_priority_group,
    _parse_vector_source_order,
    _parse_vector_source_weights,
    _super_sort_final_chunks,
    _vector_budget_observability,
    _vector_candidate_chunk_key,
    _vector_candidate_key,
    query_project,
    vector_rag_status,
)
from app.services.vector_storage import (
    _INMEMORY_CHROMA,
    _INMEMORY_CHROMADB,
    _PGVECTOR_READY_CACHE_TTL_SECONDS,
    _PGVECTOR_TABLE,
    _InMemoryChromaModule,
    _InMemoryClient,
    _InMemoryCollection,
    _chroma_collection_naming,
    _cosine_distance,
    _default_chroma_persist_dir,
    _get_collection,
    _hash_collection_name,
    _import_chromadb,
    _is_postgres,
    _legacy_collection_name,
    _migrate_chroma_collection,
    _normalize_kb_id,
    _pgvector_delete_project,
    _pgvector_hybrid_fetch,
    _pgvector_hybrid_query,
    _pgvector_literal,
    _pgvector_ready,
    _pgvector_upsert_chunks,
    _prefer_pgvector,
    _rrf_contrib,
    _rrf_score,
    _safe_json_loads,
    _vector_enabled_reason,
    ingest_chunks,
    ingest_chunks_with_embeddings,
    purge_document_vectors,
    purge_project_vectors,
    rebuild_project,
    rebuild_project_with_embeddings,
)
from app.services.vector_types import VectorChunk, VectorSource, _ALL_SOURCES

__all__ = [
    "VectorChunk",
    "VectorSource",
    "_ALL_SOURCES",
    "_PGVECTOR_TABLE",
    "_PGVECTOR_READY_CACHE_TTL_SECONDS",
    "_VECTOR_DROPPED_REASON_EXPLAIN",
    "build_project_chunks",
    "build_kb_chunk_plan",
    "ingest_chunks",
    "ingest_chunks_with_embeddings",
    "ingest_kb_vectors",
    "purge_document_vectors",
    "purge_project_vectors",
    "query_project",
    "rebuild_project",
    "rebuild_project_with_embeddings",
    "rebuild_kb_vectors",
    "run_kb_vector_operation",
    "schedule_vector_rebuild_task",
    "vector_rag_status",
    "_rerank_candidates",
    "_rerank_score",
    "_rerank_tokens",
    "_resolve_rerank_config",
    "_resolve_rerank_external_config",
    "_merge_kb_candidates",
    "_merge_kb_candidates_rrf",
    "_super_sort_final_chunks",
    "_build_vector_query_counts",
    "_vector_budget_observability",
    "_vector_candidate_key",
    "_vector_candidate_chunk_key",
    "_normalize_kb_priority_group",
    "_parse_vector_source_order",
    "_parse_vector_source_weights",
    "_is_postgres",
    "_pgvector_ready",
    "_prefer_pgvector",
    "_safe_json_loads",
    "_pgvector_literal",
    "_rrf_contrib",
    "_rrf_score",
    "_pgvector_upsert_chunks",
    "_pgvector_delete_project",
    "_pgvector_hybrid_fetch",
    "_pgvector_hybrid_query",
    "_import_chromadb",
    "_cosine_distance",
    "_InMemoryCollection",
    "_InMemoryClient",
    "_InMemoryChromaModule",
    "_INMEMORY_CHROMA",
    "_INMEMORY_CHROMADB",
    "_normalize_kb_id",
    "_legacy_collection_name",
    "_hash_collection_name",
    "_chroma_collection_naming",
    "_migrate_chroma_collection",
    "_get_collection",
    "_chunk_text",
    "_default_chroma_persist_dir",
    "_vector_enabled_reason",
]
